# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build app and upload to TestFlight"

  # TestFlight 배포
  lane :release_testflight do |options|

    match(type: "appstore")
    clear_derived_data

    increment_build_number(
        build_number: latest_testflight_build_number + 1
        )

    build_app(workspace: "PhoChak.xcworkspace", scheme: "PhoChak")

    upload_to_testflight

    version = get_version_number(
      xcodeproj: "Phochak.xcodeproj",
      target: "PhoChak"
    )
    build = get_build_number

    slack(
      message: "TestFlight 배포 완료",
      success: true,
      slack_url: "https://hooks.slack.com/services/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"
    )
  end

  # 에러 발생시 에러를 슬랙으로 알린다.
  error do |lane, exception, options|
    slack(
      message: "에러 발생: #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end